### ISSUE TITLE
Design a short answer Q/A interface.

### ISSUE THREAD

**Issue by Jax247** [cse442-spring-2020-offering/cse442-semester-project-not-the-droids-you-are-looking-for#30]
- Small text box to hold the answer, large one for questions 
- Submission button

Task Test:
Navigate to the Q/A page, type some text into the text box and press the submission button.

**Comment by alanhunt1** [comment]
Where are your task tests?  This task is not ready to come out of backlog.  What story is this linked to?  All tasks should be linked to stories.
